FROM ubuntu:18.04

WORKDIR /var/lib/

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata apache2 \
    mysql-server php php-mysql \
    libapache2-mod-php php-xml php-mbstring \
    php-acpu php-intl imagemagick inkscape \
    php-gd php-cli php-curl git curl -y && \
    mkdir -p /var/lib/mediawiki && \
    curl https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz \
    --output mediawiki-1.31.1.tar.gz && \
    tar zxf mediawiki-1.31.1.tar.gz -C /var/lib/ && \
    mv /var/lib/mediawiki-1.31.1 /var/lib/mediawiki && \
    mv /var/lib/mediawiki-1.31.1/* /var/lib/mediawiki && \
    rm -rf /var/lib/mediawiki/mediawiki-1.31.1 && \
    ln -s /var/lib/mediawiki /var/www/html/mediawiki && \
    phpenmod mbstring && \
    phpenmod xml

EXPOSE 80
EXPOSE 443
CMD ["apache2ctl","-D","FOREGROUND"]